// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:805297874644:web:c9ec5aa02b9032963c7d41',
    messagingSenderId: '805297874644',
    projectId: 'message-board-app-baffe',
    authDomain: 'message-board-app-baffe.firebaseapp.com',
    storageBucket: 'message-board-app-baffe.firebasestorage.app',
    measurementId: 'G-BQVJSC2MBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:805297874644:android:829e435d4b341e603c7d41',
    messagingSenderId: '805297874644',
    projectId: 'message-board-app-baffe',
    storageBucket: 'message-board-app-baffe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:805297874644:ios:5b4f5bc17834007a3c7d41',
    messagingSenderId: '805297874644',
    projectId: 'message-board-app-baffe',
    storageBucket: 'message-board-app-baffe.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:805297874644:ios:5b4f5bc17834007a3c7d41',
    messagingSenderId: '805297874644',
    projectId: 'message-board-app-baffe',
    storageBucket: 'message-board-app-baffe.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:805297874644:web:152c79958da3ca4f3c7d41',
    messagingSenderId: '805297874644',
    projectId: 'message-board-app-baffe',
    authDomain: 'message-board-app-baffe.firebaseapp.com',
    storageBucket: 'message-board-app-baffe.firebasestorage.app',
    measurementId: 'G-5Y5H5X7XYX',
  );
}
